-- 1. Membuat tabel logs sholat
CREATE TABLE IF NOT EXISTS public.prayer_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    subuh BOOLEAN DEFAULT false NOT NULL,
    dzuhur BOOLEAN DEFAULT false NOT NULL,
    ashar BOOLEAN DEFAULT false NOT NULL,
    maghrib BOOLEAN DEFAULT false NOT NULL,
    isya BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Membuat constraint unik untuk kombinasi user_id dan tanggal
    CONSTRAINT prayer_logs_user_id_date_key UNIQUE (user_id, date)
);

-- 2. Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.prayer_logs ENABLE ROW LEVEL SECURITY;

-- 3. Membuat policy keamanan agar pengguna hanya bisa mengakses data mereka sendiri
CREATE POLICY "Pengguna dapat melihat data sholat milik sendiri" 
ON public.prayer_logs 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menyisipkan data sholat milik sendiri" 
ON public.prayer_logs 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat memperbarui data sholat milik sendiri" 
ON public.prayer_logs 
FOR UPDATE 
USING (auth.uid() = user_id) 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menghapus data sholat milik sendiri" 
ON public.prayer_logs 
FOR DELETE 
USING (auth.uid() = user_id);
